### ISSUE TITLE
Missing Open Graph Image Tag

### ISSUE THREAD

**Issue by ronakdev** [CMSgov/dpc-app#169]
Missing og image tag means that when you share dpc.cms.gov it doesn't load a big image link and defaults to the favicon.

**Comment by jaredcunha-usds** [comment]
Good catch! I think I have a ticket for this… or at least a todo for myself somewhere. I'll need to design the asset as well.

**Comment by nickrobison-usds** [comment]
Created DPC-492. Thanks for catching this!

**Comment by nickrobison-usds** [comment]
Thanks for the issue! It should be good to go now.
