### ISSUE TITLE
Flask Demo

### ISSUE THREAD

**Issue by isears** [CMSgov/dpc-app#61]
Hi @nickrobison-usds @RickHawesUSDS 

I finally got around to finishing that flask demo app. Check it out here: https://github.com/isears/DpcFlaskExample

It's pretty basic right now, but it might help illustrate the DPC concept or even serve as an example for future DPC users. Feel free to use/not use/fork/modify as you see fit.

Cheers!
Isaac

**Comment by nickrobison-usds** [comment]
Well this is great! Thanks for continuing to work on this. Excited to pull it down and play with it!

**Comment by isears** [comment]
Sweet. Let me know if you have any questions
